# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KendoGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidgetPlayers = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetPlayers.setGeometry(QtCore.QRect(20, 70, 271, 481))
        self.listWidgetPlayers.setObjectName("listWidgetPlayers")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 221, 17))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(360, 70, 191, 25))
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 410, 141, 71))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 30, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 120, 191, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 30, 191, 21))
        self.label_5.setObjectName("label_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(360, 160, 191, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 40, 221, 17))
        self.label_3.setObjectName("label_3")
        self.listWidgetPlayers_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetPlayers_2.setGeometry(QtCore.QRect(630, 70, 271, 481))
        self.listWidgetPlayers_2.setObjectName("listWidgetPlayers_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 260, 67, 17))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 22))
        self.menubar.setObjectName("menubar")
        self.menuP_idat_hr_e = QtWidgets.QMenu(self.menubar)
        self.menuP_idat_hr_e.setObjectName("menuP_idat_hr_e")
        self.menuP_ipojit_DB_hr = QtWidgets.QMenu(self.menubar)
        self.menuP_ipojit_DB_hr.setObjectName("menuP_ipojit_DB_hr")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionP_idat_hr_e = QtWidgets.QAction(MainWindow)
        self.actionP_idat_hr_e.setObjectName("actionP_idat_hr_e")
        self.actionOdstranit_hr_e = QtWidgets.QAction(MainWindow)
        self.actionOdstranit_hr_e.setObjectName("actionOdstranit_hr_e")
        self.menuP_idat_hr_e.addAction(self.actionP_idat_hr_e)
        self.menuP_idat_hr_e.addAction(self.actionOdstranit_hr_e)
        self.menubar.addAction(self.menuP_idat_hr_e.menuAction())
        self.menubar.addAction(self.menuP_ipojit_DB_hr.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Seznam dostupných hráčů"))
        self.pushButton.setText(_translate("MainWindow", "Vytvoř turnaj"))
        self.label_2.setText(_translate("MainWindow", "Filtry:"))
        self.label_4.setText(_translate("MainWindow", "Maximální technický stupeň"))
        self.label_5.setText(_translate("MainWindow", "Minimální technický stupeň"))
        self.label_3.setText(_translate("MainWindow", "Hráči v turnaji"))
        self.label_6.setText(_translate("MainWindow", "Test"))
        self.menuP_idat_hr_e.setTitle(_translate("MainWindow", "Správa hráčů"))
        self.menuP_ipojit_DB_hr.setTitle(_translate("MainWindow", "Připojit DB hráčů"))
        self.actionP_idat_hr_e.setText(_translate("MainWindow", "Přidat hráče"))
        self.actionOdstranit_hr_e.setText(_translate("MainWindow", "Odstranit hráče"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
